// console.log()
// console.log()
// console.log('           `\\.      ,/\'')
// console.log('            |\\\\____//|')
// console.log('            )/_ `\' _\\(')
// console.log('           ,\'/-`__\'-\\`\\     < StoryLynx >')
// console.log('           /. (_><_) ,\\')
// console.log('           ` )/`--\'\\(`\'')
// console.log('             `      \'')
// console.log()
